WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py', reloading
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 19:20:02] "[35m[1mGET /mentor/m02/projects/PRJ003/students HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py', reloading
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py', reloading
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 19:21:21] "[35m[1mGET /mentor/m02/projects/PRJ003/students HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py', reloading
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 19:23:00] "[35m[1mGET /mentor/m02/projects/PRJ003/students HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py', reloading
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 19:24:11] "[35m[1mGET /mentor/m02/projects/PRJ003/students HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py', reloading
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
TypeError: project_students() got an unexpected keyword argument 'm_id'
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 19:29:09] "[35m[1mGET /mentor/m02/projects/PRJ003/students HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py', reloading
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py', reloading
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
TypeError: project_students() got an unexpected keyword argument 'm_id'
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 19:31:00] "[35m[1mGET /mentor/m02/projects/PRJ003/students HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py', reloading
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py", line 22, in login
    return fun_login()
  File "/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/login.py", line 12, in fun_login
    data = request.json
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/wrappers/request.py", line 561, in json
    return self.get_json()
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/wrappers/request.py", line 607, in get_json
    return self.on_json_loading_failed(None)
  File "/usr/local/lib/python3.8/dist-packages/flask/wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/wrappers/request.py", line 650, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 19:35:17] "[31m[1mPOST /login HTTP/1.1[0m" 415 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py', reloading
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/userAccountServices.py', reloading
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/userAccountServices.py', reloading
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 21:31:15] "POST /api/v1/accountRecovery HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/userAccountServices.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 21:36:42] "[33mPOST /api/v1/accountRecovery/ HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 21:37:17] "POST /api/v1/accountRecovery HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 21:38:16] "POST /api/v1/accountRecovery HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 21:39:18] "POST /api/v1/accountRecovery HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/login.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/userAccountServices.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/userAccountServices.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 21:43:40] "POST /api/v1/accountRecovery HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py", line 22, in login
    return fun_login()
  File "/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/login.py", line 12, in fun_login
    data = request.json
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/wrappers/request.py", line 561, in json
    return self.get_json()
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/wrappers/request.py", line 607, in get_json
    return self.on_json_loading_failed(None)
  File "/usr/local/lib/python3.8/dist-packages/flask/wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/wrappers/request.py", line 650, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 21:46:01] "[31m[1mPOST /login HTTP/1.1[0m" 415 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/userAccountServices.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 21:47:49] "POST /api/v1/accountRecovery HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/login.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 21:57:44] "[31m[1mPOST /updatepwd HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 21:57:51] "[31m[1mPOST /updatepwd HTTP/1.1[0m" 401 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py", line 54, in updatepwd
    return fun_updatepwd()
  File "/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/login.py", line 130, in fun_updatepwd
    stored_pwd = stored_pwd[0]
TypeError: 'NoneType' object is not subscriptable
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 21:58:01] "[35m[1mPOST /updatepwd HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 21:58:40] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 21:58:40] "GET /mentor/home HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 21:59:34] "[31m[1mPOST /updatepwd HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 21:59:38] "[31m[1mPOST /updatepwd HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 21:59:44] "POST /updatepwd HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/utils/authentication_utils.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/utils/authentication_utils.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/utils/authentication_utils.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/utils/authentication_utils.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/utils/authentication_utils.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py", line 38, in request_otp
    return otp_mail()
  File "/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/userAccountServices.py", line 66, in otp_mail
    cursor.execute('SELECT role_id FROM credentials WHERE username=%s',(userName))
TypeError: not all arguments converted during string formatting
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 22:03:02] "[35m[1mPOST /api/v1/accountRecovery HTTP/1.1[0m" 500 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/userAccountServices.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 22:05:14] "POST /api/v1/accountRecovery HTTP/1.1" 200 -
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 22:05:39] "[33mPOST /api/v1/accountRecovery/USRX241002 HTTP/1.1[0m" 404 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 22:07:17] "POST /api/v1/accountRecovery HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/userAccountServices.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/userAccountServices.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/userAccountServices.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/userAccountServices.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/userAccountServices.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 22:22:17] "POST /api/v1/accountRecovery HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 22:22:30] "POST /api/v1/accountRecovery HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/userAccountServices.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 22:25:07] "POST /api/v1/accountRecovery HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 22:26:43] "GET /api/v1/verifyOTP HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 22:27:23] "GET /api/v1/verifyOTP HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Feb/2024 22:28:17] "GET /api/v1/verifyOTP HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/geojoseph/Desktop/Mini Project/userprofilemanagement/app/services/userAccountServices.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 379-541-606
